export const tags = [
  { title: "Daily lift" },
  { title: "Decluttering" },
  { title: "Du học" },
  { title: "Du lịch" },
  { title: "Dọn Dẹp" },
  { title: "featured" },
  { title: "Hàn Quốc" },
  { title: "Học ngoại ngữ" },
  { title: "Khám Phá" },
  { title: "Korea" },
  { title: "Lifestyle" },
  { title: "Daily lift" },
  { title: "Daily lift" },
  { title: "Daily lift" },
  { title: "Daily lift" },
  { title: "Daily lift" },
  { title: "Daily lift" },
  { title: "Daily lift" },
  { title: "Daily lift" },
  { title: "Daily lift" },
];
