"use client";

import classNames from "classnames/bind";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import styles from "../blogs/components/Post/Post.module.scss";

const cx = classNames.bind(styles);

function AboutMeScreen() {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const data = [
    {
      photo: {
        url: "https://example.com/photo.jpg",
      },
      content: {
        raw: {
          children: [
            {
              type: "heading-three",
              children: [
                {
                  text: "Welcome to My Blog",
                },
              ],
            },
            {
              type: "paragraph",
              children: [
                {
                  text: "Hello! I’m a passionate writer sharing stories and experiences from my daily life in Hanoi. I hope you find them inspiring and insightful.",
                },
              ],
            },
            {
              type: "heading-four",
              children: [
                {
                  text: "My Journey",
                },
              ],
            },
            {
              type: "paragraph",
              children: [
                {
                  text: "I've been writing for over 5 years, and my goal is to create content that connects with readers on a personal level.",
                },
              ],
            },
            {
              type: "image",
              src: "https://example.com/journey-photo.jpg",
              title: "My Journey",
              height: 400,
              width: 600,
            },
          ],
        },
      },
    },
  ];

  const getContentFragment = (index: any, text: any, obj: any, type?: any) => {
    let modifiedText = text;

    if (obj.bold) {
      modifiedText = <b key={index}>{text}</b>;
    }
    if (obj.italic) {
      modifiedText = <em key={index}>{text}</em>;
    }
    if (obj.underline) {
      modifiedText = <u key={index}>{text}</u>;
    }

    switch (type) {
      case "heading-three":
        return (
          <h3 key={index} className="text-xl font-semibold mb-4">
            {modifiedText.map((item: any, i: any) => (
              <React.Fragment key={i}>{item}</React.Fragment>
            ))}
          </h3>
        );
      case "paragraph":
        return (
          <p key={index} className={cx("paragraph")}>
            {modifiedText.map((item: any, i: any) => (
              <React.Fragment key={i}>{item}</React.Fragment>
            ))}
          </p>
        );
      case "heading-four":
        return (
          <h4 key={index} className="text-md font-semibold mb-4">
            {modifiedText.map((item: any, i: any) => (
              <React.Fragment key={i}>{item}</React.Fragment>
            ))}
          </h4>
        );
      case "image":
        return (
          // eslint-disable-next-line @next/next/no-img-element
          <img key={index} alt={obj.title} height={obj.height} width={obj.width} src={obj.src} />
        );
      default:
        return modifiedText;
    }
  };
  return (
    <div className="container mb-8">
      <Head>
        <title>KIRA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1">
        <article className={cx("")}>
          <h1 className={cx("title")}>
            <Link href={`#`}>ABOUT ME</Link>
          </h1>
          <span className="text-left font-semibold">About Me</span>
          <div>
            <Link href={`#`}>
              <img alt="11" className={cx("img")} height={500} width="100%" src={data[0].photo.url} />
            </Link>
          </div>

          <div className="mt-1">
            {data[0].content.raw.children.map((typeObj: any, index: any) => {
              const children = typeObj.children?.map((item: any, itemIndex: any) => {
                return getContentFragment(itemIndex, item.text, item);
              });
              return getContentFragment(index, children, typeObj, typeObj.type);
            })}
          </div>
        </article>
      </div>
    </div>
  );
}

export default AboutMeScreen;
